### ISSUE TITLE
UUID using Getrandom and Rand prevents compiling to WASM

### ISSUE THREAD

**Issue by ERLindeman** [d-e-s-o/apca#50] opened 2023-02-26 23:48 UTC
Compiling any code to wasm32-unknown-unknown fails to build because of the optional Rand and Getrandom dependencies of UUID. Would it be possible to disable that option and force UUID to accomplish the same result without inheriting those child dependencies?

(Sorry for the near duplicates; trying to start a new project before vacation, and I will provide more help and clarity within a couple of weeks!)

**Comment by d-e-s-o** [comment] 2023-07-18 04:19
Seems to be a duplicate of https://github.com/d-e-s-o/apca/issues/49.

**Closed by d-e-s-o** 2023-07-18 04:19 UTC
